version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - backend

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - 127.0.0.1:8001:8001
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
